# Generated by Django 4.2.7 on 2023-11-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logger',
            old_name='requests_data',
            new_name='request_data',
        ),
        migrations.RenameField(
            model_name='logger',
            old_name='requests_ip',
            new_name='request_ip',
        ),
    ]
